version: "3"

services:
    frontend:
        build: ./frontend
        tty: true
        volumes:
            - "./frontend:/app"
        environment:
            CHOKIDAR_USEPOLLING: 1
        ports:
            - 3000:3000
        command: yarn start

    
    backend:
        build: ./backend
        tty: true
        environment:
            CHOKIDAR_USEPOLLING: 1
        volumes:
            - "./backend:/app"
        ports:
            - 8000:8000
        command: npm run start:dev

        
    mysql:
        image: mysql:5.7
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        volumes:
            - "./mysql:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=library
        ports:
            - 3306:3306
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=password
        links:
            - mysql
        ports:
            - 8080:80